name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows to workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install external packages
        run:  |
          sudo apt update
          sudo apt install -y libeigen3-dev
      - name: Run cmake setup for DEBUG build
        run: cmake -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_GRABCUT_APPS=OFF
      - name: Build DEBUG
        run: cmake --build build -j
     - name: Run grabcut
       run: cd build/tests && ./test_grabcut
      - name: Run tests
        run: |
          cd build && CTEST_OUTPUT_ON_FAILURE=1 ctest -j --progress --verbose
